name: dynamic
on: pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - uses: Swatinem/rust-cache@v2.7.7
      - uses: mozilla-actions/sccache-action@v0.0.7
      - run: cargo build --release
      - run: cargo nextest run
        env:
          RUST_LOG: debug
      - run: cargo test --doc
