name: static
on: pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2.7.7
      - uses: mozilla-actions/sccache-action@v0.0.7
      - run: cargo build --release
      - run: cargo fmt --check
      - run: cargo clippy --all-features --all --tests
